name: CI
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: build-linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Get git describe
        run: |
          git fetch --tags --prune
          echo "GIT_DESCRIBE=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Install build package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-none-eabi

      - name: Build dependencies
        run: |
          echo "Number of processors:" `nproc`
          make get-deps -j `nproc`

      - name: Build SINE firmware
        run: |
          make CONTROL=SINE clean all

      - name: Build FOC firmware
        run: |
          make CONTROL=FOC clean all

      - name: Build unit tests on host
        run: |
          make Test

      - name: Run stm32-sine unit tests on host
        run: |
          test/test_sine

      - name: Run libopeninv unit tests on host
        run: |
          libopeninv/test/test_libopeninv

      - name: Prepare firmware package contents
        run: |
          mkdir -p firmware_package
          cp stm32_sine.bin firmware_package/
          cp stm32_sine.hex firmware_package/
          cp stm32_foc.bin firmware_package/
          cp stm32_foc.hex firmware_package/
          cp misc/oi-inverter-can-map.json firmware_package/
          cp misc/oi-inverter.dbc firmware_package/
          cp misc/tesla-m3-du-foc-params.json firmware_package/

      - uses: actions/upload-artifact@v5
        with:
          name: stm32-sine-${{ env.GIT_DESCRIBE }}-firmware
          path: firmware_package
