name: Release Firmware

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Needed for git describe
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Get submodules
        run: make get-deps

      - name: Build SINE firmware
        run: make CONTROL=SINE clean all

      - name: Build FOC firmware
        run: make CONTROL=FOC clean all

      - name: Prepare firmware package
        run: |
          mkdir -p firmware_package
          cp stm32_sine.bin firmware_package/stm32_sine-${{ github.event.inputs.tag }}.bin
          cp stm32_sine.hex firmware_package/stm32_sine-${{ github.event.inputs.tag }}.hex
          cp stm32_foc.bin firmware_package/stm32_foc-${{ github.event.inputs.tag }}.bin
          cp stm32_foc.hex firmware_package/stm32_foc-${{ github.event.inputs.tag }}.hex
          cp misc/oi-inverter-can-map*.json firmware_package/
          cp misc/oi-inverter.dbc firmware_package/
          cp misc/tesla-m3-*-params.json firmware_package/
          zip -r stm32-sine-${{ github.event.inputs.tag }}-firmware.zip firmware_package/

      - name: Upload firmware package
        uses: actions/upload-artifact@v7
        with:
          name: stm32-sine-firmware
          path: stm32-sine-${{ github.event.inputs.tag }}-firmware.zip

  source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Create source tarball
        run: |
          ./scripts/git-archive-all.sh --format tar.gz --prefix stm32-sine-${{ github.event.inputs.tag }}/ stm32-sine-${{ github.event.inputs.tag }}-source.tar.gz

      - name: Upload source tarball
        uses: actions/upload-artifact@v7
        with:
          name: source-tarball
          path: stm32-sine-${{ github.event.inputs.tag }}-source.tar.gz

  release:
    needs: [build, source]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          draft: true
          prerelease: true
          files: |
            artifacts/**/stm32-sine-${{ github.event.inputs.tag }}-firmware.zip
            artifacts/**/stm32-sine-${{ github.event.inputs.tag }}-source.tar.gz
